export const cursosManana = [
  "1°1°",
  "1°2°",
  "2°1°",
  "2°2°",
  "3°1°",
  "3°2°",
  "4°1°",
  "4°2°",
  "5°1°",
  "5°2°",
  "6°1°",
  "6°2°",
];

export const cursosTarde = [
  "1°3°",
  "1°4°",
  "2°3°",
  "2°4°",
  "3°3°",
  "3°4°",
  "4°3°",
  "4°4°",
  "5°3°",
  "5°4°",
  "6°3°",
  "6°4°",
];

export const asignaturas = [
  "----------",
  "Ciencias Naturales",
  "Ciencias Sociales",
  "Educación Artística",
  "Educación Física",
  "Inglés",
  "Matemática",
  "Prácticas del Lenguaje",
  "Construcción de Ciudadanía",
  "Biología",
  "Fisicoquímica",
  "Geografía",
  "Historia",
  "Literatura",
  "Matemática Ciclo Superior",
  "NTICX",
  "Salud y Adolescencia",
  "Introducción a la Física",
  "Introducción a la Química",
  "Política y Ciudadanía",
  "Producción y Análisis de Imágenes",
  "Imagen y Nuevos Medios",
  "Art. Leng. Danza",
  "Imagen y Procedimientos Constructivos",
];

export const aniosMateria = ["1°", "2°", "3°", "4°", "5°", "6°"];

export const materiasPorAnio = {
  1: [
    "Matemática",
    "Prácticas del Lenguaje",
    "Inglés",
    "Educación Artística",
    "Educación Física",
    "Construcción de la Ciudadanía",
    "Ciencias Naturales",
    "Ciencias Sociales",
  ],
  2: [
    "Biología",
    "Construcción Ciudadana",
    "Educación Artística",
    "Educación Física",
    "Físico-Química",
    "Geografía",
    "Historia",
    "Inglés",
    "Matemática",
    "Prácticas del Lenguaje",
  ],
  3: [
    "Biología",
    "Construcción Ciudadana",
    "Educación Artística",
    "Educación Física",
    "Físico-Química",
    "Geografía",
    "Historia",
    "Inglés",
    "Matemática",
    "Prácticas del Lenguaje",
  ],
  4: [
    "Literatura",
    "Matemática Superior",
    "Educación Física",
    "Inglés",
    "Enetic",
    "SADO",
    "Introducción a la Física",
    "Biología",
    "Historia",
    "Geografía",
    "Producción y Análisis de Imágenes",
  ],
  5: [
    "Literatura",
    "Matemática Superior",
    "Educación Física",
    "Inglés",
    "Política y Ciudadanía",
    "Introducción a la Química",
    "Historia",
    "Geografía",
    "Art. Leng. Danza",
    "Imágenes y Nuevos Medios",
    "Imágenes y Procedimientos",
  ],
};